parameters:
    app.mailer.transport: sendmail
    app.mailer.template: template

services:
    lottery.winner:
        class:        SimpleLotteryBundle\Extensions\Winner
        arguments: [@doctrine.orm.entity_manager]