<?php

namespace SimpleLotteryBundle\Repository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * @return int
     */
    public function count()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            ' SELECT COUNT(p) FROM SimpleLotteryBundle:Participant p '
        );
        return $query->getSingleScalarResult();
    }

}
